export const GET_LIST_CHARACTERS = 'GET_LIST_CHARACTERS';
export const GET_LIST_CHARACTERS_SUCCESS = 'GET_LIST_CHARACTERS_SUCCESS';
export const CHARACTERS_ERROR = 'CHARACTERS_ERROR';
export const CLEAN_LIST_CHARACTERS = 'CLEAN_LIST_CHARACTERS';
export const SAVE_DETAIL_INDEX = 'SAVE_DETAIL_INDEX';